---
build_from:
  amd64: "ghcr.io/hassio-addons/base/amd64:17.2.1"
  aarch64: "ghcr.io/hassio-addons/base/aarch64:17.2.1"
name: AppDaemon
version: dev
slug: appdaemon
description: Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
url: https://github.com/hassio-addons/addon-appdaemon
webui: http://[HOST]:[PORT:5050]
arch:
  - aarch64
  - amd64
init: false
homeassistant_api: true
uart: true
ports:
  5050/tcp: 5050
  6000/tcp: 6000
  6001/udp: 6001

ports_description:
  5050/tcp: AppDaemon
  6000/tcp: Camera 1 input
  6001/udp: Camera 2 input

map:
  - addon_config:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
  - config:rw

options:
  system_packages: []
  python_packages: []
  init_commands: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  system_packages:
    - str
  python_packages:
    - str
  init_commands:
    - str
